### ISSUE TITLE
Add option at start to use a pre-canned example

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/delimiter#9]
As a Visitor I want to try this out quickly so that I have an idea what this does and if it is relevant to me

=> provide a pre-canned url to github csv they can use that demonstrates this app

Here's a sample from a mockup (file upload rather than github / gitlab csv):

![image](https://user-images.githubusercontent.com/180658/53002523-c6c86680-3424-11e9-8b19-ff22b670b1a4.png)

**Comment by timwis** [comment]
Great idea
